### ISSUE TITLE
Xivelyへの接続が切れる

### ISSUE THREAD

**Issue by dodo5522** [dodo5522/radiation_monitor#13]
時々Xivelyサーバから切断される模様。
送信の旅にXivelyインスタンスを生成するように変更するか、例外を補足してリトライするか。

```
Exception in thread XivelyEventHandler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/Downloads/radiation_monitor/src/event-listener/event_listener/base.py", line 110, in _thread_mai
n
    self.run_in_condition_(got_data)
  File "/home/pi/Downloads/radiation_monitor/src/event-listener/event_listener/handler.py", line 140, in _run
    self.client_.update()
  File "/usr/local/lib/python2.7/dist-packages/xively/models.py", line 138, in update
    self._manager.update(url, **state)
  File "/usr/local/lib/python2.7/dist-packages/xively/managers.py", line 146, in update
    response = self.client.put(url, data=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 528, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/xively/client.py", line 77, in request
    return super(Client, self).request(method, full_url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by dodo5522** [comment]
これで多分治る。
https://github.com/dodo5522/event_listener/issues/1

**Comment by dodo5522** [comment]
あれ、直っていない？

**Comment by dodo5522** [comment]
raspberry pi側のpyenv環境がおかしかったせいで治っていないように見えていた。
習性済み。
