### ISSUE TITLE
中途半端な状態で監視を始めるとUnicodeEncodeError/ValueErrorが発生する事がある

### ISSUE THREAD

**Issue by dodo5522** [dodo5522/radiation_monitor#14]
```
2016/10/05 PM  9:20:13 radiation_monitor DEBUG: UnicodeEncodeError raised in GeigerMeter.
Exception in thread GeigerMeter:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/radiation_monitor/source.py", line 71, in run
    cpm = wait_for_radiation()
  File "/usr/local/lib/python2.7/dist-packages/radiation_monitor/source.py", line 64, in wait_for_radiation
    return int(self.uart_.readline().decode("ascii").split()[0])
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-58453: invalid decimal Unicode string
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/radiation_monitor/source.py", line 71, in run
    cpm = wait_for_radiation()
  File "/usr/local/lib/python2.7/dist-packages/radiation_monitor/source.py", line 64, in wait_for_radiation
    return int(self.uart_.readline().decode("ascii").split()[0])
ValueError: invalid literal for int() with base 10: '1pm'
```

**Comment by dodo5522** [comment]
event_handlerパッケージ側で解決。
