### ISSUE TITLE
Xivelyへの接続が切れる その２

### ISSUE THREAD

**Issue by dodo5522** [dodo5522/radiation_monitor#15]
```
2017/01/06 PM  1:35:34 radiation_monitor DEBUG: 2017-01-06 04:35:34.867189: Count Per Minute: 11[cpm]
2017/01/06 PM  1:36:33 radiation_monitor DEBUG: 2017-01-06 04:36:33.986293: Micro Sievert Per Hour: 0.15428[usv]
2017/01/06 PM  1:36:33 radiation_monitor DEBUG: 2017-01-06 04:36:33.986293: Count Per Minute: 19[cpm]
Exception in thread XivelyEventHandler:
Traceback (most recent call last):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_reques
t
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 387, in _make_reques
t
    httplib_response = conn.getresponse()
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 325, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='api.xively.com', port=80): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/event_listener/handler.py", line 160, in _run
    self._feed.update()
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/xively/models.py", line 138, in update
    self._manager.update(url, **state)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/xively/managers.py", line 146, in update
    response = self.client.put(url, data=kwargs)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/sessions.py", line 528, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/xively/client.py", line 77, in request
    return super(Client, self).request(method, full_url, *args, **kwargs)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='api.xively.com', port=80): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by dodo5522** [comment]
今度は503。  
なんなんだ。。。

```
Traceback (most recent call last):
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/event_listener/base.py", line 110, in _thread_main
    self.run_in_condition_(got_data)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/event_listener/handler.py", line 168, in _run
    self._feed = self._api.feeds.get(self._feed_key)
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/xively/managers.py", line 264, in get
    response.raise_for_status()
  File "/home/pi/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://api.xively.com/v2/feeds/1031061917
```
